import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { AuthProvider } from '@/contexts/AuthContext'

const aeonik = localFont({
  src: [
    {
      path: '../../public/fonts/AeonikTRIAL-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/AeonikTRIAL-Regular.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/AeonikTRIAL-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-aeonik',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "mini-project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${aeonik.className} ${aeonik.variable}`}
        style={{ fontFamily: 'var(--font-aeonik)' }}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
